parameters:
#    ximo_prueba_bundle_prueba.example.class: XimoPruebaBundle\PruebaBundle\Example

services:
#    ximo_prueba_bundle_prueba.example:
#        class: %ximo_prueba_bundle_prueba.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
