ximo_prueba_bundle_prueba:
    resource: "@XimoPruebaBundlePruebaBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

